### ISSUE TITLE
SKT전용관 이슈

### ISSUE THREAD

**Issue by lsw6875** [soju6jan/oksusu#1]
안녕하세요^^
SKT 관에서 mid 가 바뀌어서 안들어지나 싶어서 변경해봤는데 안되네요.. 리스트는 잘 가져오는거 보니 그 문제는 아닌것 같고.. 에러로그에는 play 에러가 발생하더라구요..

ERROR: Playlist Player: skipping unplayable item:0, path[plugin://plugin.video.oksusu/?pageNo=None&mode=PlayVideo&param=%7BF1DAA2C7-3C2B-47D3-XFDT-C5763FAAC911%7D&param2=None]

저 주소 값은 확실히 PC랑 확인 하니 웹 url 값이 제대로 넘어온거던데.. 왜 에러가 나는 걸까요?

**Comment by soju6jan** [comment]
답변이 너무 늦었네요. 죄송합니다.
로그파일을 주시면 확인해보겠습니다.
