### ISSUE TITLE
KODI에서 옥수수 애드온 실행시 "시청불가"

### ISSUE THREAD

**Issue by pms0811** [soju6jan/oksusu#2]
어제 문의 드리고 난 다음 집에가서 혹시나 하고 애드온 삭제후 재 실행 하였더니 잘 됩니다.
컴퓨터/뷰잉/휴대폰 3개의 단말기에서 동시에 안되서 서버에서 막았나 했는데 그게 아니였나 봅니다.
어찌 한번에 3개가 다 안되는 현상이 나왔던 걸까요.
3개다 삭제후 재설치 하니깐 잘 됩니다.
번거롭게 해드려 죄송합니다.
이슈 클로즈 부탁드립니다.

**Comment by soju6jan** [comment]
다행이네요.
